/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.24.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Observed attachment access state.
 */
export interface AttachmentStatus {
    /**
     * Public permalink for the attachment. Local storage usually exposes a public URL, while object storage may  expose the object URL.
     */
    'permalink'?: string;
    /**
     * Generated thumbnail URLs keyed by thumbnail size name.
     */
    'thumbnails'?: { [key: string]: string; };
}

