/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.24.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Observed state of a category.
 */
export interface CategoryStatus {
    /**
     * Absolute permalink calculated from the category permalink policy.
     */
    'permalink'?: string;
    /**
     * Total number of posts in this category and all descendant categories.
     */
    'postCount'?: number;
    /**
     * Total number of published and public posts in this category and all descendant categories.
     */
    'visiblePostCount'?: number;
}

