/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.24.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Desired display, hierarchy, and rendering configuration of a category.
 */
export interface CategorySpec {
    /**
     * Child category extension names.
     */
    'children'?: Array<string>;
    /**
     * Cover image URL or attachment URI of the category.
     */
    'cover'?: string;
    /**
     * Human-readable description of the category.
     */
    'description'?: string;
    /**
     * Display name of the category.
     */
    'displayName': string;
    /**
     * Whether this category tree and its posts should be hidden from theme-side lists.
     */
    'hideFromList'?: boolean;
    /**
     * Theme template used to render posts associated with this category when the post does not specify its own template.
     */
    'postTemplate'?: string;
    /**
     * Whether ancestor category post queries should stop cascading into this category\'s children.
     */
    'preventParentPostCascadeQuery'?: boolean;
    /**
     * Sorting priority. Larger values are ordered ahead by consumers that sort by priority.
     */
    'priority': number;
    /**
     * URL slug of the category.
     */
    'slug': string;
    /**
     * Theme template used to render the category archive page.
     */
    'template'?: string;
}

