/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.24.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Identity of a comment or reply owner.
 */
export interface CommentOwner {
    /**
     * Additional owner metadata, such as avatar, website, or email hash.
     */
    'annotations'?: { [key: string]: string; };
    /**
     * Display name shown for the owner.
     */
    'displayName'?: string;
    /**
     * Owner identity kind. Built-in values are User and Email.
     */
    'kind': string;
    /**
     * Owner identifier. For User owners, this is the User metadata.name; for Email owners, an email address.
     */
    'name': string;
}

