/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.22.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CopyOperation {
    /**
     * A JSON Pointer path pointing to the location to move/copy from.
     */
    'from': string;
    'op': CopyOperationOpEnum;
    /**
     * A JSON Pointer path pointing to the location to move/copy from.
     */
    'path': string;
}

export const CopyOperationOpEnum = {
    Copy: 'copy'
} as const;

export type CopyOperationOpEnum = typeof CopyOperationOpEnum[keyof typeof CopyOperationOpEnum];


