/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The subject name of reason type to be interested in
 * @export
 * @interface InterestReasonSubject
 */
export interface InterestReasonSubject {
    /**
     * 
     * @type {string}
     * @memberof InterestReasonSubject
     */
    'apiVersion': string;
    /**
     * 
     * @type {string}
     * @memberof InterestReasonSubject
     */
    'kind': string;
    /**
     * if name is not specified, it presents all subjects of the specified reason type and custom resources
     * @type {string}
     * @memberof InterestReasonSubject
     */
    'name'?: string;
}

