/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.24.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Excerpt } from './excerpt';

/**
 * Desired content, publication, taxonomy, and rendering configuration of a post.
 */
export interface PostSpec {
    /**
     * Whether new comments are allowed for this post.
     */
    'allowComment': boolean;
    /**
     * Base snapshot name used to apply snapshot patches.
     */
    'baseSnapshot'?: string;
    /**
     * Category extension names associated with the post.
     */
    'categories'?: Array<string>;
    /**
     * Cover image URL or attachment URI of the post.
     */
    'cover'?: string;
    /**
     * Whether the post is logically deleted and should be treated as recycled.
     */
    'deleted': boolean;
    'excerpt': Excerpt;
    /**
     * Snapshot name of the latest draft content.
     */
    'headSnapshot'?: string;
    /**
     * HTML meta tag attribute maps injected into the post template head.
     */
    'htmlMetas'?: Array<{ [key: string]: string; }>;
    /**
     * Username of the post owner.
     */
    'owner'?: string;
    /**
     * Whether the post should be pinned ahead of normal post ordering.
     */
    'pinned': boolean;
    /**
     * Sorting priority. Larger values are ordered ahead by consumers that sort by priority.
     */
    'priority': number;
    /**
     * Desired publish state. False keeps or moves the post to draft.
     */
    'publish': boolean;
    /**
     * Time when the post was published or is scheduled to be published.
     */
    'publishTime'?: string;
    /**
     * Snapshot name selected as the released version for theme-side rendering after publishing.
     */
    'releaseSnapshot'?: string;
    /**
     * URL slug of the post.
     */
    'slug': string;
    /**
     * Tag extension names associated with the post.
     */
    'tags'?: Array<string>;
    /**
     * Theme template used to render this post.
     */
    'template'?: string;
    /**
     * Display title of the post.
     */
    'title': string;
    /**
     * Visibility of the post in theme-side queries. Only PUBLIC content is returned to anonymous visitors.
     */
    'visible': PostSpecVisibleEnum;
}

export const PostSpecVisibleEnum = {
    Public: 'PUBLIC',
    Internal: 'INTERNAL',
    Private: 'PRIVATE'
} as const;

export type PostSpecVisibleEnum = typeof PostSpecVisibleEnum[keyof typeof PostSpecVisibleEnum];


