/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReasonSelector
 */
export interface ReasonSelector {
    /**
     * 
     * @type {string}
     * @memberof ReasonSelector
     */
    'language': string;
    /**
     * 
     * @type {string}
     * @memberof ReasonSelector
     */
    'reasonType': string;
}

