/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.24.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Selector used to match a notification template to a reason type and language.
 */
export interface ReasonSelector {
    /**
     * Language tag this template applies to, or default for the fallback template.
     */
    'language': string;
    /**
     * ReasonType metadata.name this template applies to.
     */
    'reasonType': string;
}

