/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.24.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SettingForm } from './setting-form';

/**
 * Collection of form groups that make up this setting definition.
 */
export interface SettingSpec {
    /**
     * Form groups rendered for this setting definition.
     */
    'forms': Array<SettingForm>;
}

