/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.22.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Metadata } from './metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { SinglePageSpec } from './single-page-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { SinglePageStatus } from './single-page-status';

/**
 * <p>Single page extension.</p>
 */
export interface SinglePage {
    'apiVersion': string;
    'kind': string;
    'metadata': Metadata;
    'spec': SinglePageSpec;
    'status'?: SinglePageStatus;
}

