/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.24.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Aggregated visit, upvote, and comment counters for a content resource.
 */
export interface Stats {
    /**
     * Total approved comment count.
     */
    'approvedComment'?: number;
    /**
     * Total comment count, including comments that may not be approved.
     */
    'totalComment'?: number;
    /**
     * Total upvote count.
     */
    'upvote'?: number;
    /**
     * Total visit count.
     */
    'visit'?: number;
}

