/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.20.11-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Metadata } from './metadata';
// May contain unused imports in some cases
// @ts-ignore
import { SubscriptionSpec } from './subscription-spec';

/**
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'apiVersion': string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'kind': string;
    /**
     * 
     * @type {Metadata}
     * @memberof Subscription
     */
    'metadata': Metadata;
    /**
     * 
     * @type {SubscriptionSpec}
     * @memberof Subscription
     */
    'spec'?: SubscriptionSpec;
}

