/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.26.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Metadata } from './metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionSpec } from './subscription-spec';

/**
 * Subscription extension that records which subscriber should be notified when a matching reason is triggered.   <p>It holds a {@link Subscriber Subscriber} to the user to be notified, a {@link InterestReason InterestReason} to subscribe to.
 */
export interface Subscription {
    'apiVersion': string;
    'kind': string;
    'metadata': Metadata;
    'spec'?: SubscriptionSpec;
}

