/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The subscriber to be notified
 * @export
 * @interface SubscriptionSubscriber
 */
export interface SubscriptionSubscriber {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionSubscriber
     */
    'name'?: string;
}

