/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.27.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A sudo confirmation method available to the current user.
 */
export interface SudoMethod {
    /**
     * optional masked destination shown in the UI
     */
    'maskedTarget'?: string;
    /**
     * method name, such as <code>totp</code> or <code>email</code>
     */
    'name': string;
    /**
     * whether a one-time code must be sent first
     */
    'sendable': boolean;
}

