/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.24.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Observed state of a tag.
 */
export interface TagStatus {
    /**
     * Metadata version observed by the last successful reconciliation.
     */
    'observedVersion'?: number;
    /**
     * Absolute permalink calculated from the tag permalink policy.
     */
    'permalink'?: string;
    /**
     * Total number of posts associated with the tag.
     */
    'postCount'?: number;
    /**
     * Total number of published and public posts associated with the tag.
     */
    'visiblePostCount'?: number;
}

