/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.24.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Condition } from './condition';

/**
 * Observed theme lifecycle and installation state.
 */
export interface ThemeStatus {
    /**
     * Reconciliation conditions for the theme.
     */
    'conditions'?: Array<Condition>;
    /**
     * Whether the theme appears to be a local development workspace.
     */
    'inDevelopment'?: boolean;
    /**
     * Local filesystem location where the theme is loaded from.
     */
    'location'?: string;
    /**
     * Current theme lifecycle phase.
     */
    'phase'?: ThemeStatusPhaseEnum;
    /**
     * Resolved preview screenshot URL served from the theme root.
     */
    'screenshot'?: string;
}

export const ThemeStatusPhaseEnum = {
    Ready: 'READY',
    Failed: 'FAILED',
    Unknown: 'UNKNOWN'
} as const;

export type ThemeStatusPhaseEnum = typeof ThemeStatusPhaseEnum[keyof typeof ThemeStatusPhaseEnum];


