/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.17.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Role } from './role';

/**
 * 
 * @export
 * @interface UserPermission
 */
export interface UserPermission {
    /**
     * 
     * @type {Array<Role>}
     * @memberof UserPermission
     */
    'permissions': Array<Role>;
    /**
     * 
     * @type {Set<Role>}
     * @memberof UserPermission
     */
    'roles': Set<Role>;
    /**
     * 
     * @type {Set<string>}
     * @memberof UserPermission
     */
    'uiPermissions': Set<string>;
}

