# 提供了 timestamp、username 变量，用于初始化数据时填充时间戳和用户名
# 初始化文章关联的分类、标签数据
apiVersion: content.halo.run/v1alpha1
kind: Category
metadata:
  name: 76514a40-6ef1-4ed9-b58a-e26945bde3ca
spec:
  displayName: 默认分类
  slug: default
  description: 这是你的默认分类，如不需要，删除即可。
  cover: ""
  template: ""
  priority: 0
  children: [ ]
status:
  permalink: "/categories/default"

---
apiVersion: content.halo.run/v1alpha1
kind: Tag
metadata:
  name: c33ceabb-d8f1-4711-8991-bb8f5c92ad7c
spec:
  displayName: Halo
  slug: halo
  color: "#ffffff"
  cover: ""
status:
  permalink: "/tags/halo"

---
# 文章关联的内容
apiVersion: content.halo.run/v1alpha1
kind: Snapshot
metadata:
  name: fb5cd6bd-998d-4ccc-984d-5cc23b0a09f9
  annotations:
    content.halo.run/keep-raw: "true"
spec:
  subjectRef:
    group: content.halo.run
    version: v1alpha1
    kind: Post
    name: 5152aea5-c2e8-4717-8bba-2263d46e19d5
  rawType: HTML
  rawPatch: <h2 id="hello-halo"><strong>Hello
    Halo</strong></h2><p>如果你看到了这一篇文章，那么证明你已经安装成功了，感谢使用 <a target="_blank"
    rel="noopener noreferrer nofollow" href="https://www.halo.run/">Halo</a>
    进行创作，希望能够使用愉快。</p><h2
    id="%E7%9B%B8%E5%85%B3%E9%93%BE%E6%8E%A5"><strong>相关链接</strong></h2><ul><li><p>官网：<a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://www.halo.run">https://www.halo.run</a></p></li><li><p>文档：<a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://docs.halo.run">https://docs.halo.run</a></p></li><li><p>社区：<a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://bbs.halo.run">https://bbs.halo.run</a></p></li><li><p>应用市场：<a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://www.halo.run/store/apps">https://www.halo.run/store/apps</a></p></li><li><p>开源地址：<a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://github.com/halo-dev/halo">https://github.com/halo-dev/halo</a></p></li></ul><p>在使用过程中，有任何问题都可以通过以上链接找寻答案，或者联系我们。</p><blockquote><p>这是一篇自动生成的文章，请删除这篇文章之后开始你的创作吧！</p></blockquote>
  contentPatch: <h2 id="hello-halo"><strong>Hello
    Halo</strong></h2><p>如果你看到了这一篇文章，那么证明你已经安装成功了，感谢使用 <a target="_blank"
    rel="noopener noreferrer nofollow" href="https://www.halo.run/">Halo</a>
    进行创作，希望能够使用愉快。</p><h2
    id="%E7%9B%B8%E5%85%B3%E9%93%BE%E6%8E%A5"><strong>相关链接</strong></h2><ul><li><p>官网：<a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://www.halo.run">https://www.halo.run</a></p></li><li><p>文档：<a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://docs.halo.run">https://docs.halo.run</a></p></li><li><p>社区：<a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://bbs.halo.run">https://bbs.halo.run</a></p></li><li><p>应用市场：<a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://www.halo.run/store/apps">https://www.halo.run/store/apps</a></p></li><li><p>开源地址：<a
    target="_blank" rel="noopener noreferrer nofollow"
    href="https://github.com/halo-dev/halo">https://github.com/halo-dev/halo</a></p></li></ul><p>在使用过程中，有任何问题都可以通过以上链接找寻答案，或者联系我们。</p><blockquote><p>这是一篇自动生成的文章，请删除这篇文章之后开始你的创作吧！</p></blockquote>
  lastModifyTime: "${timestamp}"
  owner: "${username}"
  contributors:
    - "${username}"

---
# 初始化文章数据
apiVersion: content.halo.run/v1alpha1
kind: Post
metadata:
  name: 5152aea5-c2e8-4717-8bba-2263d46e19d5
spec:
  title: Hello Halo
  slug: hello-halo
  releaseSnapshot: fb5cd6bd-998d-4ccc-984d-5cc23b0a09f9
  headSnapshot: fb5cd6bd-998d-4ccc-984d-5cc23b0a09f9
  baseSnapshot: fb5cd6bd-998d-4ccc-984d-5cc23b0a09f9
  owner: "${username}"
  template: ""
  cover: ""
  deleted: false
  publish: true
  publishTime: "${timestamp}"
  pinned: false
  allowComment: true
  visible: PUBLIC
  priority: 0
  excerpt:
    autoGenerate: false
    raw: 如果你看到了这一篇文章，那么证明你已经安装成功了，感谢使用 Halo 进行创作，希望能够使用愉快。
  categories:
    - 76514a40-6ef1-4ed9-b58a-e26945bde3ca
  tags:
    - c33ceabb-d8f1-4711-8991-bb8f5c92ad7c
  htmlMetas: [ ]
status:
  permalink: /archives/hello-halo

---
# 自定义页面关联的内容
apiVersion: content.halo.run/v1alpha1
kind: Snapshot
metadata:
  name: c3f73cc2-194e-4cd8-9092-7386aa50a0e5
  annotations:
    content.halo.run/keep-raw: "true"
spec:
  subjectRef:
    group: content.halo.run
    version: v1alpha1
    kind: SinglePage
    name: 373a5f79-f44f-441a-9df1-85a4f553ece8
  rawType: HTML
  rawPatch: <h2><strong>关于页面</strong></h2><p>这是一个自定义页面，你可以在后台的 <code>页面</code>
    -&gt; <code>自定义页面</code>
    找到它，你可以用于新建关于页面、联系我们页面等等。</p><blockquote><p>这是一篇自动生成的页面，你可以在后台删除它。</p></blockquote>
  contentPatch: <h2><strong>关于页面</strong></h2><p>这是一个自定义页面，你可以在后台的 <code>页面</code>
    -&gt; <code>自定义页面</code>
    找到它，你可以用于新建关于页面、联系我们页面等等。</p><blockquote><p>这是一篇自动生成的页面，你可以在后台删除它。</p></blockquote>
  lastModifyTime: "${timestamp}"
  owner: "${username}"
  contributors:
    - "${username}"

---
# 初始化自定义页面数据
apiVersion: content.halo.run/v1alpha1
kind: SinglePage
metadata:
  name: 373a5f79-f44f-441a-9df1-85a4f553ece8
spec:
  title: 关于
  slug: about
  template: ""
  cover: ""
  owner: "${username}"
  deleted: false
  publish: true
  baseSnapshot: c3f73cc2-194e-4cd8-9092-7386aa50a0e5
  headSnapshot: c3f73cc2-194e-4cd8-9092-7386aa50a0e5
  releaseSnapshot: c3f73cc2-194e-4cd8-9092-7386aa50a0e5
  pinned: false
  allowComment: true
  visible: PUBLIC
  version: 1
  priority: 0
  excerpt:
    autoGenerate: false
    raw: 这是一个自定义页面，你可以在后台的 页面 -> 自定义页面 找到它，你可以用于新建关于页面、联系我们页面等等。
  htmlMetas: [ ]
status:
  permalink: "/about"

---
# 首页菜单项
apiVersion: v1alpha1
kind: MenuItem
metadata:
  name: 88c3f10b-321c-4092-86a8-70db00251b74
spec:
  displayName: 首页
  href: /
  children: [ ]
  priority: 0
---
# 关联到文章作为菜单
apiVersion: v1alpha1
kind: MenuItem
metadata:
  name: c4c814d1-0c2c-456b-8c96-4864965fee94
spec:
  displayName: "Hello Halo"
  href: "/archives/hello-halo"
  children: [ ]
  priority: 1
  targetRef:
    group: content.halo.run
    version: v1alpha1
    kind: Post
    name: 5152aea5-c2e8-4717-8bba-2263d46e19d5
---
# 关联到标签作为菜单
apiVersion: v1alpha1
kind: MenuItem
metadata:
  name: 35869bd3-33b5-448b-91ee-cf6517a59644
spec:
  displayName: "Halo"
  href: "/tags/halo"
  children: [ ]
  priority: 2
  targetRef:
    group: content.halo.run
    version: v1alpha1
    kind: Tag
    name: c33ceabb-d8f1-4711-8991-bb8f5c92ad7c
---
# 关联到自定义页面作为菜单
apiVersion: v1alpha1
kind: MenuItem
metadata:
  name: b0d041fa-dc99-48f6-a193-8604003379cf
spec:
  displayName: "关于"
  href: "/about"
  children: [ ]
  priority: 3
  targetRef:
    group: content.halo.run
    version: v1alpha1
    kind: SinglePage
    name: 373a5f79-f44f-441a-9df1-85a4f553ece8
---
apiVersion: v1alpha1
kind: Menu
metadata:
  name: primary
spec:
  displayName: 主菜单
  menuItems:
    - 88c3f10b-321c-4092-86a8-70db00251b74
    - c4c814d1-0c2c-456b-8c96-4864965fee94
    - 35869bd3-33b5-448b-91ee-cf6517a59644
    - b0d041fa-dc99-48f6-a193-8604003379cf
