apiVersion: v1alpha1
kind: "Role"
metadata:
  name: anonymous
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
rules:
  - apiGroups: [ "api.console.halo.run" ]
    resources: [ "comments", "comments/reply" ]
    verbs: [ "create" ]
