apiVersion: v1alpha1
kind: "Role"
metadata:
  name: anonymous
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
rules:
  - apiGroups: [ "api.halo.run" ]
    resources: [ "comments", "comments/reply" ]
    verbs: [ "create", "get", "list" ]
  - apiGroups: [ "api.halo.run" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - nonResourceURLs: [ "/apis/api.halo.run/v1alpha1/trackers/*" ]
    verbs: [ "create" ]
