apiVersion: v1alpha1
kind: "Role"
metadata:
  name: authenticated
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      [ 
        "role-template-own-user-info",
        "role-template-own-permissions",
        "role-template-change-own-password",
        "role-template-stats",
        "role-template-annotation-setting"
      ]
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames: [ "system-states" ]
    verbs: [ "get" ]
  - apiGroups: [ "api.console.halo.run" ]
    resources: [ "auth-providers" ]
    verbs: [ "list" ]
---
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-own-user-info
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
rules:
  - apiGroups: [ "api.console.halo.run" ]
    resources: [ "users" ]
    resourceNames: [ "-" ]
    verbs: [ "get", "update" ]
---
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-own-permissions
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
rules:
  - apiGroups: [ "api.console.halo.run" ]
    resources: [ "users/permissions" ]
    resourceNames: [ "-" ]
    verbs: [ "list", "get" ]
---
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-change-own-password
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
rules:
  - apiGroups: [ "api.console.halo.run" ]
    resources: [ "users/password" ]
    resourceNames: [ "-" ]
    verbs: [ "update" ]
---
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-stats
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
rules:
  - apiGroups: [ "api.console.halo.run" ]
    resources: [ "stats" ]
    verbs: [ "get", "list" ]

---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-annotation-setting
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
rules:
  - apiGroups: [ "" ]
    resources: [ "annotationsettings" ]
    verbs: [ "get", "list" ]