apiVersion: v1alpha1
kind: "Role"
metadata:
  name: anonymous
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      [ "role-template-own-user-info", "role-template-own-permissions"]
rules:
  - apiGroups: [ "api.halo.run" ]
    resources: [ "comments", "comments/reply" ]
    verbs: [ "create", "get", "list" ]
  - apiGroups: [ "api.halo.run" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - nonResourceURLs: [ "/apis/api.halo.run/v1alpha1/trackers/*" ]
    verbs: [ "create" ]
  - nonResourceURLs: [ "/actuator/globalinfo", "/actuator/health", "/actuator/health/*", "/login/public-key"]
    verbs: [ "get" ]
