apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-manage-settings
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: "[ \"role-template-view-settings\" ]"
    rbac.authorization.halo.run/module: "Settings Management"
    rbac.authorization.halo.run/display-name: "设置管理"
rules:
  - apiGroups: [ "" ]
    resources: [ "settings" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
---
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-view-settings
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Settings Management"
    rbac.authorization.halo.run/display-name: "设置查看"
rules:
  - apiGroups: [ "" ]
    resources: [ "settings" ]
    verbs: [ "get", "list" ]
