apiVersion: plugin.halo.run/v1alpha1
kind: SearchEngine
metadata:
  name: lucene
spec:
  logo: https://lucene.apache.org/theme/images/lucene/lucene_logo_green_300.png
  website: https://lucene.apache.org/
  displayName: Lucene
  description: Apache Lucene is a high-performance, full-featured search engine library written entirely in Java. It is a technology suitable for nearly any application that requires structured search, full-text search, faceting, nearest-neighbor search across high-dimensionality vectors, spell correction or query suggestions.
  postSearchImpl: run.halo.app.search.post.LucenePostSearchService
