apiVersion: v1alpha1
kind: Setting
metadata:
  name: system
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          label: "站点标题"
          name: title
          validation: required
        - $formkit: text
          label: "站点副标题"
          name: subtitle
        - $formkit: text
          label: Logo
          name: logo
        - $formkit: text
          label: Favicon
          name: favicon
    - group: post
      label: 文章设置
      formSchema:
        - $formkit: select
          label: "列表排序方式"
          name: sortOrder
          value: "publishTime"
          options:
            visitCount: "浏览量"
            publishTime: "发布时间"
            updateTime: "更新时间"
          validation: required
        - $formkit: number
          label: "列表显示条数"
          name: pageSize
          value: 10
          min: 1
          max: 100
          validation: required
        - $formkit: checkbox
          label: "新文章审核"
          value: false
          name: review
          help: "用户发布文章是否需要管理员审核"
    - group: seo
      label: SEO 设置
      formSchema:
        - $formkit: checkbox
          name: blockSpiders
          label: "屏蔽搜索引擎"
          value: false
        - $formkit: textarea
          name: keywords
          label: "站点关键词"
        - $formkit: textarea
          name: description
          label: "站点描述"
    - group: comment
      label: 评论设置
      formSchema:
        - $formkit: checkbox
          name: enable
          value: true
          label: "启用评论"
        - $formkit: checkbox
          name: requireReviewForNew
          value: true
          label: "新评论审核"
        - $formkit: checkbox
          name: systemUserOnly
          value: true
          label: "仅允许注册用户评论"
    - group: routeRules
      label: 主题路由设置
      formSchema:
        - $formkit: text
          label: "分类页路由前缀"
          value: "categories"
          name: categories
          validation: required | alphanumeric
        - $formkit: text
          label: "标签页路由前缀"
          value: "tags"
          name: tags
          validation: required | alphanumeric
        - $formkit: text
          label: "归档页路由前缀"
          value: "archives"
          name: archives
          validation: required | alphanumeric
        - $formkit: select
          label: 文章详情页访问规则
          value: '/archives/{slug}'
          options:
            - label: '/archives/{slug}'
              value: '/archives/{slug}'
            - label: '/archives/{name}'
              value: '/archives/{name}'
            - label: '/?p={name}'
              value: '/?p={name}'
            - label: '/?p={slug}'
              value: '/?p={slug}'
            - label: '/{year}/{slug}'
              value: '/{year:\d{4}}/{slug}'
            - label: '/{year}/{month}/{slug}'
              value: '/{year:\d{4}}/{month:\d{2}}/{slug}'
            - label: '/{year}/{month}/{day}/{slug}'
              value: '/{year:\d{4}}/{month:\d{2}}/{day:\d{2}}/{slug}'
          name: post
          validation: required
    - group: codeInjection
      label: 代码注入
      formSchema:
        - $formkit: textarea
          label: "全局 head 标签"
          name: globalHead
          help: "注入代码到所有页面的 head 标签部分"
        - $formkit: textarea
          label: "内容页 head 标签"
          name: contentHead
          help: "注入代码到文章页面和自定义页面的 head 标签部分"
        - $formkit: textarea
          label: "页脚"
          name: footer
          help: "注入代码到所有页面的页脚部分"
