apiVersion: v1alpha1
kind: User
metadata:
  name: anonymousUser
spec:
  displayName: Anonymous User
  email: anonymous@example.com
  disabled: true

---
apiVersion: v1alpha1
kind: User
metadata:
  name: ghost
spec:
  displayName: 已删除用户
  email: ghost@example.com
  disabled: true
  bio: 该用户已被删除。

