server:
  port: 8090
  forward-headers-strategy: native
  compression:
    enabled: false
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

halo:
  download-timeout: 5m
  auth-enabled: true
  mode: demo
  workDir: ${user.home}/halo-demo/
  cache: memory
