spring:
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/halo
    username: root
    password: mariadb
  sql:
    init:
      mode: always
      platform: mysql
halo:
  console:
    proxy:
      endpoint: http://localhost:3000/
      enabled: true
  security:
    initializer:
      super-admin-username: admin
      super-admin-password: admin