export const users = [
  {
    id: 1,
    name: "Ryan Wang",
    username: "ryanwang",
    role: "Super Administrator",
    email: "i@ryanc.cc",
    avatar: "https://ryanc.cc/avatar",
  },
  {
    id: 2,
    name: "JohnNiang",
    username: "johnniang",
    role: "Super Administrator",
    email: "johnniang@halo.run",
    avatar: "https://johnniang.me/avatar",
  },
  {
    id: 3,
    name: "guqing",
    username: "guqing",
    role: "Super Administrator",
    email: "guqing@halo.run",
    avatar: "https://guqing.xyz/avatar",
  },
  {
    id: 4,
    name: "Johnson",
    username: "johnson",
    role: "Administrator",
    email: "",
    avatar: "https://i.pravatar.cc/300?name=johnson",
  },
  {
    id: 5,
    name: "Mary Jane",
    username: "maryjane",
    role: "Editor",
    email: "",
    avatar: "https://i.pravatar.cc/300?name=maryjane",
  },
  {
    id: 5,
    name: "Berry Allen",
    username: "flash",
    role: "Guest",
    email: "",
    avatar: "https://i.pravatar.cc/300?name=flash",
  },
];
