title=完善资料
form.email.label=邮箱
form.code.label=验证码
form.code.sendButton=发送验证码
form.submit=提交
form.email.emptyValidation=请输入邮箱
form.error.invalidCode=验证码错误或已过期
form.error.codeRequired=请先发送并填写验证码
form.error.emailInUse=邮箱已被其他用户使用
form.error.sendCodeFailed=发送验证码失败，请稍后重试。
form.logout=退出登录
