name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    id: preface
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: markdown
    id: environment
    attributes:
      value: "## Environment"
  - type: textarea
    id: system-information
    attributes:
      label: "System information"
      description: "Access the actuator page of the Console, click the copy button in the upper right corner, and paste the information here."
    validations:
      required: true
  - type: dropdown
    id: operation-method
    validations:
      required: true
    attributes:
      label: "What is the project operation method?"
      options:
        - Docker
        - Docker Compose
        - Fat Jar
        - Source Code
  - type: markdown
    id: details
    attributes:
      value: "## Details"
  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "For ease of management, please do not report multiple unrelated issues under the same issue."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Relevant log output"
      description: "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: "Additional information"
      description: "If you have other information to note, you can fill it in here (screenshots, videos, etc.)."
