name: Bug 反馈
description: 提交 Bug 反馈
labels: [bug]
body:
  - type: markdown
    id: preface
    attributes:
      value: |
        感谢你花时间填写此错误报告！在开始之前，我们非常推荐阅读一遍[《开源最佳实践》](https://github.com/LinuxSuRen/open-source-best-practice)，这会在很大程度上提高我们彼此的效率。
  - type: markdown
    id: environment
    attributes:
      value: "## 环境信息"
  - type: textarea
    id: system-information
    attributes:
      label: "系统信息"
      description: "访问 Console 的概览页面，点击右上角的复制按钮，将信息粘贴到此处。"
    validations:
      required: true
  - type: dropdown
    id: operation-method
    validations:
      required: true
    attributes:
      label: "使用的哪种方式运行？"
      options:
        - Docker
        - Docker Compose
        - Fat Jar
        - Source Code
  - type: markdown
    id: details
    attributes:
      value: "## 详细信息"
  - type: textarea
    id: what-happened
    attributes:
      label: "发生了什么？"
      description: "为了方便我们管理，请不要在同一个 issue 下报告多个不相关的问题。"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "相关日志输出"
      description: "请复制并粘贴任何相关的日志输出。这将自动格式化为代码，因此无需反引号。"
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: "附加信息"
      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"
