name: 新特性建议
description: 提交新特性建议
body:
  - type: markdown
    id: preface
    attributes:
      value: |
        你好！感谢你为 Halo 提交新特性建议。在开始之前，我们非常推荐阅读一遍[《开源软件指南》](https://opensource.guide/zh-hans/)，这会在很大程度上提高我们彼此的效率。

        **在提交之前，请检查：**

        - 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
        - 这是和 Halo 相关的特性，如果是非项目本身的问题，建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
        - 如果是插件和主题特性建议，请在对应的插件和主题仓库提交。
  - type: markdown
    id: environment
    attributes:
      value: "## 环境信息"
  - type: input
    id: version
    attributes:
      label: "你当前使用的版本"
  - type: markdown
    id: details
    attributes:
      value: "## 详细信息"
  - type: textarea
    id: description
    attributes:
      label: "描述一下此特性"
      description: "为了方便我们管理，请不要在同一个 issue 下提交多个没有相关性的特性。"
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: "附加信息"
      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"