/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Condition } from "./condition";

/**
 *
 * @export
 * @interface ThemeStatus
 */
export interface ThemeStatus {
  /**
   *
   * @type {Array<Condition>}
   * @memberof ThemeStatus
   */
  conditions?: Array<Condition>;
  /**
   *
   * @type {string}
   * @memberof ThemeStatus
   */
  location?: string;
  /**
   *
   * @type {string}
   * @memberof ThemeStatus
   */
  phase?: ThemeStatusPhaseEnum;
}

export const ThemeStatusPhaseEnum = {
  Ready: "READY",
  Failed: "FAILED",
  Unknown: "UNKNOWN",
} as const;

export type ThemeStatusPhaseEnum =
  typeof ThemeStatusPhaseEnum[keyof typeof ThemeStatusPhaseEnum];
