version: '3.1'
services:
  testing:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - halo
    depends_on:
      halo:
        condition: service_healthy
  halo:
    image: ghcr.io/halo-dev/halo-dev:${TAG:-main}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 8090:8090
