import type { DashboardResponsiveLayout } from "@halo-dev/console-shared";

const DefaultResponsiveLayouts: DashboardResponsiveLayout = {
  lg: [
    {
      i: "79187a8d-1c35-497f-a55e-05c0a6258660",
      x: 0,
      y: 0,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:post:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "96a9ac85-ec47-4c4b-bd02-184ee047f6a5",
      x: 6,
      y: 0,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:comment:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "ee42743e-06d8-4106-9481-42443bb8b2f0",
      x: 3,
      y: 0,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:user:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "19a92835-c12d-486b-9546-f16bd7a7da98",
      x: 9,
      y: 0,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:view:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "e45cd079-a406-42de-a196-e11c64f6d893",
      x: 0,
      y: 3,
      w: 6,
      h: 12,
      minW: 3,
      minH: 6,
      id: "core:quick-action",
      config: {
        enabled_items: [
          "core:user-center",
          "core:theme-preview",
          "core:new-post",
          "core:new-page",
          "core:upload-attachment",
          "core:theme-manage",
          "core:plugin-manage",
          "core:new-user",
          "core:refresh-search-engine",
        ],
      },
    },
    {
      i: "3bcd12eb-44ee-48e8-a37f-3f5d73470e2d",
      x: 6,
      y: 3,
      w: 6,
      h: 12,
      minW: 3,
      minH: 6,
      id: "core:notifications",
      config: {},
    },
  ],
  xs: [
    {
      i: "2026e492-0832-4a27-b44b-ab076e31ec17",
      x: 0,
      y: 0,
      w: 2,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:post:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "7c868acd-10e8-4e92-99f3-ff00b4aa4ec4",
      x: 2,
      y: 0,
      w: 2,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:user:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "90b458dc-679e-4b59-b0a9-86b02cf6ae59",
      x: 0,
      y: 3,
      w: 2,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:comment:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "bb71aa3a-1170-4e1d-a0f3-290b4ca77ca1",
      x: 2,
      y: 3,
      w: 2,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:view:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "c3e467a7-9a15-4732-9ba1-45f36a49d25e",
      x: 0,
      y: 6,
      w: 6,
      h: 12,
      minW: 3,
      minH: 6,
      id: "core:quick-action",
      config: {
        enabled_items: [
          "core:user-center",
          "core:theme-preview",
          "core:new-post",
          "core:new-page",
          "core:upload-attachment",
          "core:theme-manage",
          "core:plugin-manage",
          "core:new-user",
          "core:refresh-search-engine",
        ],
      },
    },
    {
      i: "24005fc4-e725-4e6d-95ae-f83026ffc178",
      x: 0,
      y: 18,
      w: 6,
      h: 12,
      minW: 3,
      minH: 6,
      id: "core:notifications",
      config: {},
    },
  ],
  xxs: [
    {
      i: "2026e492-0832-4a27-b44b-ab076e31ec17",
      x: 0,
      y: 0,
      w: 2,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:post:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "7c868acd-10e8-4e92-99f3-ff00b4aa4ec4",
      x: 2,
      y: 0,
      w: 2,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:user:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "90b458dc-679e-4b59-b0a9-86b02cf6ae59",
      x: 0,
      y: 3,
      w: 2,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:comment:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "bb71aa3a-1170-4e1d-a0f3-290b4ca77ca1",
      x: 2,
      y: 3,
      w: 2,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:view:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "c3e467a7-9a15-4732-9ba1-45f36a49d25e",
      x: 0,
      y: 6,
      w: 6,
      h: 12,
      minW: 3,
      minH: 6,
      id: "core:quick-action",
      config: {
        enabled_items: [
          "core:user-center",
          "core:theme-preview",
          "core:new-post",
          "core:new-page",
          "core:upload-attachment",
          "core:theme-manage",
          "core:plugin-manage",
          "core:new-user",
          "core:refresh-search-engine",
        ],
      },
    },
    {
      i: "24005fc4-e725-4e6d-95ae-f83026ffc178",
      x: 0,
      y: 18,
      w: 6,
      h: 12,
      minW: 3,
      minH: 6,
      id: "core:notifications",
      config: {},
    },
  ],
  md: [
    {
      i: "d86c4b16-9cf5-4d1e-9f46-fc79693c76f2",
      x: 0,
      y: 0,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:post:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "31a29ecc-e2d6-449c-9850-994e2fd6d9c6",
      x: 6,
      y: 0,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:comment:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "b3cc217f-5008-49bd-b6a3-b760c1afc4f9",
      x: 3,
      y: 0,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:user:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "b7afa21f-c24b-4fa2-9c98-de06e3c48687",
      x: 9,
      y: 0,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:view:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "1f329a9f-d1aa-4337-98b3-34d8732b9143",
      x: 0,
      y: 3,
      w: 6,
      h: 12,
      minW: 3,
      minH: 6,
      id: "core:quick-action",
      config: {
        enabled_items: [
          "core:user-center",
          "core:theme-preview",
          "core:new-post",
          "core:new-page",
          "core:upload-attachment",
          "core:theme-manage",
          "core:plugin-manage",
          "core:new-user",
          "core:refresh-search-engine",
        ],
      },
    },
    {
      i: "ac9a9984-da16-4d81-adc6-8c64ffcbde5e",
      x: 6,
      y: 3,
      w: 6,
      h: 12,
      minW: 3,
      minH: 6,
      id: "core:notifications",
      config: {},
    },
  ],
  sm: [
    {
      i: "61298416-1b09-426d-914c-ba7664825626",
      x: 0,
      y: 0,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:post:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "44932f76-7667-4b77-99e7-9778c8f54062",
      x: 0,
      y: 3,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:comment:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "d6508199-b7a3-47dc-aabf-4e3634760b78",
      x: 3,
      y: 0,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:user:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "3525a65d-2c69-4c0f-a378-6c9f1f06ad4c",
      x: 3,
      y: 3,
      w: 3,
      h: 3,
      minW: 2,
      minH: 2,
      id: "core:view:stats",
      config: {
        enable_animation: true,
      },
    },
    {
      i: "1bf7eba4-2805-495b-85cd-ebd9ecd9ab82",
      x: 0,
      y: 6,
      w: 6,
      h: 12,
      minW: 3,
      minH: 6,
      id: "core:quick-action",
      config: {
        enabled_items: [
          "core:user-center",
          "core:theme-preview",
          "core:new-post",
          "core:new-page",
          "core:upload-attachment",
          "core:theme-manage",
          "core:plugin-manage",
          "core:new-user",
          "core:refresh-search-engine",
        ],
      },
    },
    {
      i: "06dc350c-db0e-46ea-9718-cef1e5bca339",
      x: 0,
      y: 18,
      w: 6,
      h: 12,
      minW: 3,
      minH: 6,
      id: "core:notifications",
      config: {},
    },
  ],
};

export { DefaultResponsiveLayouts };
