#!/bin/bash

./gradlew clean build -x test

echo "=> Building the binary"
docker run \
  -v $(pwd):/src \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -w="/src" \
  openjdk:8-jdk-alpine \
  ./gradlew clean build -x test
echo "=> Built the binary successfully"