## TODO: Currently, Halo does not support i18n for configuration file descriptions
## So Simplified Chinese is temporarily used as the default description language.

apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: additional-webfilter
spec:
  className: run.halo.app.security.AdditionalWebFilter
  displayName: "附加 Web 过滤器"
  type: MULTI_INSTANCE
  description: "用于 Web 请求的链式处理，可以用来实现跨领域、与应用无关的需求，如安全性、超时等"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: reactive-post-content-handler
spec:
  className: run.halo.app.theme.ReactivePostContentHandler
  displayName: "文章内容处理器"
  type: MULTI_INSTANCE
  description: "扩展在主题侧显示的文章内容"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: reactive-singlepage-content-handler
spec:
  className: run.halo.app.theme.ReactiveSinglePageContentHandler
  displayName: "页面内容处理器"
  type: MULTI_INSTANCE
  description: "扩展在主题侧显示的页面内容"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: comment-widget
spec:
  className: run.halo.app.theme.dialect.CommentWidget
  displayName: "评论组件"
  type: SINGLETON
  description: "扩展在文章页面中显示的评论组件"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: username-password-authentication-manager
spec:
  className: run.halo.app.security.authentication.login.UsernamePasswordAuthenticationManager
  displayName: "用户名密码认证管理器"
  type: SINGLETON
  description: "扩展用户名密码认证"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: reactive-notifier
spec:
  className: run.halo.app.notification.ReactiveNotifier
  displayName: "消息通知器"
  type: MULTI_INSTANCE
  description: "扩展消息通知器，以向用户发送通知"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: search-engine
spec:
  className: run.halo.app.search.SearchEngine
  displayName: "搜索引擎"
  type: SINGLETON
  description: "扩展内容搜索引擎"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: template-footer-processor
spec:
  className: run.halo.app.theme.dialect.TemplateFooterProcessor
  displayName: 页脚标签内容处理器
  type: MULTI_INSTANCE
  description: "提供用于扩展 <halo:footer/> 标签内容的扩展方式。"
---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: excerpt-generator
spec:
  className: run.halo.app.content.ExcerptGenerator
  displayName: 摘要生成器
  type: SINGLETON
  description: "提供自动生成摘要的方式扩展，如使用算法提取或使用 AI 生成。"
---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: thumbnail-provider
spec:
  className: run.halo.app.core.attachment.ThumbnailProvider
  displayName: 图片缩略图生成
  type: MULTI_INSTANCE
  description: "提供生成图片缩略图的扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: attachment-handler
spec:
  className: run.halo.app.core.extension.attachment.endpoint.AttachmentHandler
  displayName: "附件存储策略"
  type: MULTI_INSTANCE
  description: "提供附件上传、删除和存储的扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: comment-subject
spec:
  className: run.halo.app.content.comment.CommentSubject
  displayName: "评论主体"
  type: MULTI_INSTANCE
  description: "提供评论主体展示的扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: template-head-processor
spec:
  className: run.halo.app.theme.dialect.TemplateHeadProcessor
  displayName: "页头内容处理器"
  type: MULTI_INSTANCE
  description: "提供用于扩展主题页面 <head> 标签内容的扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: element-tag-post-processor
spec:
  className: run.halo.app.theme.dialect.ElementTagPostProcessor
  displayName: "元素标签后置处理器"
  type: MULTI_INSTANCE
  description: "提供用于对 Thymeleaf 元素标签进行后置处理的扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: before-security-webfilter
spec:
  className: run.halo.app.security.BeforeSecurityWebFilter
  displayName: "Security 前置过滤器"
  type: MULTI_INSTANCE
  description: "提供在 Security 过滤器链最前面执行的 Web 过滤器扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: after-security-webfilter
spec:
  className: run.halo.app.security.AfterSecurityWebFilter
  displayName: "Security 后置过滤器"
  type: MULTI_INSTANCE
  description: "提供在 Security 过滤器链最后面执行的 Web 过滤器扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: http-basic-security-webfilter
spec:
  className: run.halo.app.security.HttpBasicSecurityWebFilter
  displayName: "HTTP Basic 认证过滤器"
  type: MULTI_INSTANCE
  description: "提供 HTTP Basic 认证逻辑的扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: form-login-security-webfilter
spec:
  className: run.halo.app.security.FormLoginSecurityWebFilter
  displayName: "表单登录认证过滤器"
  type: MULTI_INSTANCE
  description: "提供表单登录认证逻辑的扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: authentication-security-webfilter
spec:
  className: run.halo.app.security.AuthenticationSecurityWebFilter
  displayName: "普通认证过滤器"
  type: MULTI_INSTANCE
  description: "提供普通认证逻辑的扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: anonymous-authentication-security-webfilter
spec:
  className: run.halo.app.security.AnonymousAuthenticationSecurityWebFilter
  displayName: "匿名认证过滤器"
  type: MULTI_INSTANCE
  description: "提供匿名认证逻辑的扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: oauth2-authorization-code-security-webfilter
spec:
  className: run.halo.app.security.OAuth2AuthorizationCodeSecurityWebFilter
  displayName: "OAuth2 授权码认证过滤器"
  type: MULTI_INSTANCE
  description: "提供 OAuth2 授权码认证逻辑的扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: halo-documents-provider
spec:
  className: run.halo.app.search.HaloDocumentsProvider
  displayName: "搜索文档提供者"
  type: MULTI_INSTANCE
  description: "提供用于重建搜索索引的文档数据"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: user-pre-creating-handler
spec:
  className: run.halo.app.core.user.service.UserPreCreatingHandler
  displayName: "用户创建前处理器"
  type: MULTI_INSTANCE
  description: "提供在用户创建之前执行自定义逻辑的扩展方式"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: user-post-creating-handler
spec:
  className: run.halo.app.core.user.service.UserPostCreatingHandler
  displayName: "用户创建后处理器"
  type: MULTI_INSTANCE
  description: "提供在用户创建之后执行自定义逻辑的扩展方式"
