apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-manage-cache
  deletionTimestamp: 2024-06-01T00:00:00Z
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Cache Management"
    rbac.authorization.halo.run/display-name: "Cache Manage"
    rbac.authorization.halo.run/ui-permissions: |
      ["system:caches:manage"]
rules:
  - apiGroups: ["api.console.halo.run"]
    resources: ["caches"]
    verbs: ["delete"]
