/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { UserDevice } from '../models';
/**
 * ConsoleApiSecurityHaloRunV1alpha1DeviceApi - axios parameter creator
 * @export
 */
export const ConsoleApiSecurityHaloRunV1alpha1DeviceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List all user devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDevices: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/apis/console.api.security.halo.run/v1alpha1/devices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BasicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ConsoleApiSecurityHaloRunV1alpha1DeviceApi - functional programming interface
 * @export
 */
export const ConsoleApiSecurityHaloRunV1alpha1DeviceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ConsoleApiSecurityHaloRunV1alpha1DeviceApiAxiosParamCreator(configuration)
    return {
        /**
         * List all user devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDevices(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDevice>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDevices(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConsoleApiSecurityHaloRunV1alpha1DeviceApi.listDevices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ConsoleApiSecurityHaloRunV1alpha1DeviceApi - factory interface
 * @export
 */
export const ConsoleApiSecurityHaloRunV1alpha1DeviceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ConsoleApiSecurityHaloRunV1alpha1DeviceApiFp(configuration)
    return {
        /**
         * List all user devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDevices(options?: RawAxiosRequestConfig): AxiosPromise<UserDevice> {
            return localVarFp.listDevices(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ConsoleApiSecurityHaloRunV1alpha1DeviceApi - object-oriented interface
 * @export
 * @class ConsoleApiSecurityHaloRunV1alpha1DeviceApi
 * @extends {BaseAPI}
 */
export class ConsoleApiSecurityHaloRunV1alpha1DeviceApi extends BaseAPI {
    /**
     * List all user devices
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConsoleApiSecurityHaloRunV1alpha1DeviceApi
     */
    public listDevices(options?: RawAxiosRequestConfig) {
        return ConsoleApiSecurityHaloRunV1alpha1DeviceApiFp(this.configuration).listDevices(options).then((request) => request(this.axios, this.basePath));
    }
}

