/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { Role } from '../models';
// @ts-ignore
import { RoleList } from '../models';
/**
 * V1alpha1RoleApi - axios parameter creator
 * @export
 */
export const V1alpha1RoleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create v1alpha1/Role
         * @param {Role} [role] Fresh role
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createV1alpha1Role: async (role?: Role, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1alpha1/roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BasicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(role, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete v1alpha1/Role
         * @param {string} name Name of role
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteV1alpha1Role: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('deleteV1alpha1Role', 'name', name)
            const localVarPath = `/api/v1alpha1/roles/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BasicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get v1alpha1/Role
         * @param {string} name Name of role
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1alpha1Role: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('getV1alpha1Role', 'name', name)
            const localVarPath = `/api/v1alpha1/roles/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BasicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List v1alpha1/Role
         * @param {number} [page] Page number. Default is 0.
         * @param {number} [size] Size number. Default is 0.
         * @param {Array<string>} [labelSelector] Label selector. e.g.: hidden!&#x3D;true
         * @param {Array<string>} [fieldSelector] Field selector. e.g.: metadata.name&#x3D;&#x3D;halo
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listV1alpha1Role: async (page?: number, size?: number, labelSelector?: Array<string>, fieldSelector?: Array<string>, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1alpha1/roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BasicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (labelSelector) {
                localVarQueryParameter['labelSelector'] = labelSelector;
            }

            if (fieldSelector) {
                localVarQueryParameter['fieldSelector'] = fieldSelector;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update v1alpha1/Role
         * @param {string} name Name of role
         * @param {Role} [role] Updated role
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateV1alpha1Role: async (name: string, role?: Role, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('updateV1alpha1Role', 'name', name)
            const localVarPath = `/api/v1alpha1/roles/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BasicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(role, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * V1alpha1RoleApi - functional programming interface
 * @export
 */
export const V1alpha1RoleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = V1alpha1RoleApiAxiosParamCreator(configuration)
    return {
        /**
         * Create v1alpha1/Role
         * @param {Role} [role] Fresh role
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createV1alpha1Role(role?: Role, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Role>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createV1alpha1Role(role, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1alpha1RoleApi.createV1alpha1Role']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete v1alpha1/Role
         * @param {string} name Name of role
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteV1alpha1Role(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteV1alpha1Role(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1alpha1RoleApi.deleteV1alpha1Role']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get v1alpha1/Role
         * @param {string} name Name of role
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1alpha1Role(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Role>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getV1alpha1Role(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1alpha1RoleApi.getV1alpha1Role']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List v1alpha1/Role
         * @param {number} [page] Page number. Default is 0.
         * @param {number} [size] Size number. Default is 0.
         * @param {Array<string>} [labelSelector] Label selector. e.g.: hidden!&#x3D;true
         * @param {Array<string>} [fieldSelector] Field selector. e.g.: metadata.name&#x3D;&#x3D;halo
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listV1alpha1Role(page?: number, size?: number, labelSelector?: Array<string>, fieldSelector?: Array<string>, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoleList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listV1alpha1Role(page, size, labelSelector, fieldSelector, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1alpha1RoleApi.listV1alpha1Role']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update v1alpha1/Role
         * @param {string} name Name of role
         * @param {Role} [role] Updated role
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateV1alpha1Role(name: string, role?: Role, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Role>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateV1alpha1Role(name, role, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1alpha1RoleApi.updateV1alpha1Role']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * V1alpha1RoleApi - factory interface
 * @export
 */
export const V1alpha1RoleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = V1alpha1RoleApiFp(configuration)
    return {
        /**
         * Create v1alpha1/Role
         * @param {V1alpha1RoleApiCreateV1alpha1RoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createV1alpha1Role(requestParameters: V1alpha1RoleApiCreateV1alpha1RoleRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Role> {
            return localVarFp.createV1alpha1Role(requestParameters.role, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete v1alpha1/Role
         * @param {V1alpha1RoleApiDeleteV1alpha1RoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteV1alpha1Role(requestParameters: V1alpha1RoleApiDeleteV1alpha1RoleRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteV1alpha1Role(requestParameters.name, options).then((request) => request(axios, basePath));
        },
        /**
         * Get v1alpha1/Role
         * @param {V1alpha1RoleApiGetV1alpha1RoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1alpha1Role(requestParameters: V1alpha1RoleApiGetV1alpha1RoleRequest, options?: RawAxiosRequestConfig): AxiosPromise<Role> {
            return localVarFp.getV1alpha1Role(requestParameters.name, options).then((request) => request(axios, basePath));
        },
        /**
         * List v1alpha1/Role
         * @param {V1alpha1RoleApiListV1alpha1RoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listV1alpha1Role(requestParameters: V1alpha1RoleApiListV1alpha1RoleRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<RoleList> {
            return localVarFp.listV1alpha1Role(requestParameters.page, requestParameters.size, requestParameters.labelSelector, requestParameters.fieldSelector, requestParameters.sort, options).then((request) => request(axios, basePath));
        },
        /**
         * Update v1alpha1/Role
         * @param {V1alpha1RoleApiUpdateV1alpha1RoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateV1alpha1Role(requestParameters: V1alpha1RoleApiUpdateV1alpha1RoleRequest, options?: RawAxiosRequestConfig): AxiosPromise<Role> {
            return localVarFp.updateV1alpha1Role(requestParameters.name, requestParameters.role, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createV1alpha1Role operation in V1alpha1RoleApi.
 * @export
 * @interface V1alpha1RoleApiCreateV1alpha1RoleRequest
 */
export interface V1alpha1RoleApiCreateV1alpha1RoleRequest {
    /**
     * Fresh role
     * @type {Role}
     * @memberof V1alpha1RoleApiCreateV1alpha1Role
     */
    readonly role?: Role
}

/**
 * Request parameters for deleteV1alpha1Role operation in V1alpha1RoleApi.
 * @export
 * @interface V1alpha1RoleApiDeleteV1alpha1RoleRequest
 */
export interface V1alpha1RoleApiDeleteV1alpha1RoleRequest {
    /**
     * Name of role
     * @type {string}
     * @memberof V1alpha1RoleApiDeleteV1alpha1Role
     */
    readonly name: string
}

/**
 * Request parameters for getV1alpha1Role operation in V1alpha1RoleApi.
 * @export
 * @interface V1alpha1RoleApiGetV1alpha1RoleRequest
 */
export interface V1alpha1RoleApiGetV1alpha1RoleRequest {
    /**
     * Name of role
     * @type {string}
     * @memberof V1alpha1RoleApiGetV1alpha1Role
     */
    readonly name: string
}

/**
 * Request parameters for listV1alpha1Role operation in V1alpha1RoleApi.
 * @export
 * @interface V1alpha1RoleApiListV1alpha1RoleRequest
 */
export interface V1alpha1RoleApiListV1alpha1RoleRequest {
    /**
     * Page number. Default is 0.
     * @type {number}
     * @memberof V1alpha1RoleApiListV1alpha1Role
     */
    readonly page?: number

    /**
     * Size number. Default is 0.
     * @type {number}
     * @memberof V1alpha1RoleApiListV1alpha1Role
     */
    readonly size?: number

    /**
     * Label selector. e.g.: hidden!&#x3D;true
     * @type {Array<string>}
     * @memberof V1alpha1RoleApiListV1alpha1Role
     */
    readonly labelSelector?: Array<string>

    /**
     * Field selector. e.g.: metadata.name&#x3D;&#x3D;halo
     * @type {Array<string>}
     * @memberof V1alpha1RoleApiListV1alpha1Role
     */
    readonly fieldSelector?: Array<string>

    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @type {Array<string>}
     * @memberof V1alpha1RoleApiListV1alpha1Role
     */
    readonly sort?: Array<string>
}

/**
 * Request parameters for updateV1alpha1Role operation in V1alpha1RoleApi.
 * @export
 * @interface V1alpha1RoleApiUpdateV1alpha1RoleRequest
 */
export interface V1alpha1RoleApiUpdateV1alpha1RoleRequest {
    /**
     * Name of role
     * @type {string}
     * @memberof V1alpha1RoleApiUpdateV1alpha1Role
     */
    readonly name: string

    /**
     * Updated role
     * @type {Role}
     * @memberof V1alpha1RoleApiUpdateV1alpha1Role
     */
    readonly role?: Role
}

/**
 * V1alpha1RoleApi - object-oriented interface
 * @export
 * @class V1alpha1RoleApi
 * @extends {BaseAPI}
 */
export class V1alpha1RoleApi extends BaseAPI {
    /**
     * Create v1alpha1/Role
     * @param {V1alpha1RoleApiCreateV1alpha1RoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1alpha1RoleApi
     */
    public createV1alpha1Role(requestParameters: V1alpha1RoleApiCreateV1alpha1RoleRequest = {}, options?: RawAxiosRequestConfig) {
        return V1alpha1RoleApiFp(this.configuration).createV1alpha1Role(requestParameters.role, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete v1alpha1/Role
     * @param {V1alpha1RoleApiDeleteV1alpha1RoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1alpha1RoleApi
     */
    public deleteV1alpha1Role(requestParameters: V1alpha1RoleApiDeleteV1alpha1RoleRequest, options?: RawAxiosRequestConfig) {
        return V1alpha1RoleApiFp(this.configuration).deleteV1alpha1Role(requestParameters.name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get v1alpha1/Role
     * @param {V1alpha1RoleApiGetV1alpha1RoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1alpha1RoleApi
     */
    public getV1alpha1Role(requestParameters: V1alpha1RoleApiGetV1alpha1RoleRequest, options?: RawAxiosRequestConfig) {
        return V1alpha1RoleApiFp(this.configuration).getV1alpha1Role(requestParameters.name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List v1alpha1/Role
     * @param {V1alpha1RoleApiListV1alpha1RoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1alpha1RoleApi
     */
    public listV1alpha1Role(requestParameters: V1alpha1RoleApiListV1alpha1RoleRequest = {}, options?: RawAxiosRequestConfig) {
        return V1alpha1RoleApiFp(this.configuration).listV1alpha1Role(requestParameters.page, requestParameters.size, requestParameters.labelSelector, requestParameters.fieldSelector, requestParameters.sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update v1alpha1/Role
     * @param {V1alpha1RoleApiUpdateV1alpha1RoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1alpha1RoleApi
     */
    public updateV1alpha1Role(requestParameters: V1alpha1RoleApiUpdateV1alpha1RoleRequest, options?: RawAxiosRequestConfig) {
        return V1alpha1RoleApiFp(this.configuration).updateV1alpha1Role(requestParameters.name, requestParameters.role, options).then((request) => request(this.axios, this.basePath));
    }
}

