plugins {
  id 'idea'
  id 'base'
  alias(libs.plugins.node)
  alias(libs.plugins.openapi.generator)
}

idea {
  module {
    excludeDirs += file('node_modules/')
    excludeDirs += file('packages').listFiles().collect {
      file(it.path + '/node_modules/')
    }
    excludeDirs += file('packages').listFiles().collect {
      file(it.path + '/dist/')
    }
  }
}

pnpmInstall {
  nodeModulesOutputFilter {
    exclude('**')
  }
}

tasks.named('clean') {
  dependsOn tasks.named('doClean')
}

tasks.register('doClean', Delete) {
  delete layout.buildDirectory
  delete fileTree('packages') {
    include '*/dist/**'
  }
}

tasks.named('assemble') {
  dependsOn tasks.named('doBuild')
}

tasks.register('doBuild', PnpmTask) {
  dependsOn tasks.named('pnpmInstall')
  pnpmCommand = ['run', 'build']
  inputs.files(fileTree(layout.projectDirectory) {
    include 'console-src/**', 'uc-src/**', 'src/**', 'public/**', 'packages/**', '*.js', '*.json', '*.yaml', '*.html'
    exclude '**/node_modules/**', '**/build/**', '**/dist/**'
  })
  outputs.dir(layout.buildDirectory.dir('dist'))
}

tasks.register('test', PnpmTask) {
  dependsOn tasks.named('pnpmInstall')
  pnpmCommand = ['run', 'test:unit']
  mustRunAfter tasks.named('lint'), tasks.named('typecheck')
}

tasks.register('lint', PnpmTask) {
  dependsOn tasks.named('pnpmInstall')
  pnpmCommand = ['run', 'lint']
}

tasks.register('typecheck', PnpmTask) {
  dependsOn tasks.named('pnpmInstall')
  pnpmCommand = ['run', 'typecheck']
  mustRunAfter tasks.named('lint')
}

tasks.named('check') {
  dependsOn tasks.named('lint'), tasks.named('typecheck'), tasks.named('test')
}

tasks.register('dev', PnpmTask) {
  dependsOn tasks.named('pnpmInstall')
  pnpmCommand = ['run', 'dev']
}
