packages:
  - packages/**
catalog:
  "@vitest/ui": 4.1.10
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.5
  vitest: 4.1.10
overrides:
  vite: "catalog:"
  vite-plus: "catalog:"
  vitest: "catalog:"
  "@lezer/javascript": 1.5.4
  prosemirror-model: 1.25.1
  prosemirror-transform: 1.10.4
  prosemirror-view: 1.40.0
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vite-plus: 0.2.0
    vitest: "*"
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@openapitools/openapi-generator-cli"
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - vue-demi
patchedDependencies:
  "@tiptap/extension-drag-handle@3.29.0": patches/@tiptap__extension-drag-handle@3.29.0.patch
