export const posts = [
  {
    id: 514,
    title: "Halo 1.5.3 发布",
    status: "PUBLISHED",
    slug: "halo-153-released",
    editorType: "MARKDOWN",
    updateTime: 1652087983741,
    createTime: 1652087543478,
    editTime: 1652087983738,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-153-released.html",
    summary:
      "Improvements优化邮件发送异常信息处理。 halo-dev/halo#1860 @ntdgy @superdgy优化静态存储的资源映射处理逻辑，支持手动操作 .halo/static 目录后，在后台通过刷新按钮更新资源映射。 halo-dev/halo#1907 @Yhcrown @muy",
    thumbnail: "https://halo.run/upload/2022/05/1.5.3.png",
    visits: 156,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 1128,
    inProgress: false,
    commentCount: 3,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 511,
    title: "Halo 1.5.2 发布",
    status: "PUBLISHED",
    slug: "halo-152-released",
    editorType: "MARKDOWN",
    updateTime: 1649582521222,
    createTime: 1649580837197,
    editTime: 1649582521202,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-152-released.html",
    summary:
      "Improvements保存文章的时候不再保存内容到 posts 表，originalContent 和 formatContent 已经是废弃字段。 halo-dev/halo#1797 @guqing优化 Markdown 文档导入的 FrontMatter 的解析规则。 halo-dev/ha",
    thumbnail: "https://halo.run/upload/2022/03/1.5.0.png",
    visits: 1700,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 1483,
    inProgress: false,
    commentCount: 5,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 479,
    title: "Halo 1.5.1 发布",
    status: "PUBLISHED",
    slug: "halo-151-released",
    editorType: "MARKDOWN",
    updateTime: 1648634917957,
    createTime: 1648634014575,
    editTime: 1648634917948,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-151-released.html",
    summary:
      "Bug Fixes修复文章加密和分类加密功能的逻辑问题。 halo-dev/halo#1781 halo-dev/halo#1785 @guqing @qiany-sui修复文章和分类的链接带有中文时从密码页重定向到详情页面提示 404 的问题。 halo-dev/halo#1786 @guqing",
    thumbnail: "https://halo.run/upload/2022/03/1.5.0.png",
    visits: 1007,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 1050,
    inProgress: false,
    commentCount: 7,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 447,
    title: "Halo 1.5.0 发布",
    status: "PUBLISHED",
    slug: "halo-150-released",
    editorType: "MARKDOWN",
    updateTime: 1648025027976,
    createTime: 1648007074766,
    editTime: 1648025027971,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-150-released.html",
    summary:
      "距离我们 2020 年 9 月 24 号发布 1.4.0 已经过去了 545 天了，期间虽然有一些版本更新，但大多数都是 patch 修复版本。终于，在今天正式发布 1.5.0 版本。其中带来了大量的优化更新，下面为大家简单介绍一些亮点功能，详细更新日志可在本文末尾查阅。版本亮点文章表拆分在此版本中",
    thumbnail: "https://halo.run/upload/2022/03/1.5.0.png",
    visits: 1085,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 5852,
    inProgress: false,
    commentCount: 1,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 415,
    title: "Butterfly",
    status: "PUBLISHED",
    slug: "butterfly",
    editorType: "MARKDOWN",
    updateTime: 1649680073984,
    createTime: 1642992439970,
    editTime: 1649680073975,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/butterfly.html",
    summary:
      "Butterfly 主题 Halo 移植版Butterfly 是Hexo社区hexo-theme-Butterfly 此次移植Halo由原版的 pug模板引擎 调整为 freemarker， 保持灵活性的同时最大限度的移植了原版功能，希望大家喜欢 ❤️ \uD83C\uDF38 同时也要在此感谢原作者 Jerry 欢迎",
    thumbnail: "https://halo.run/upload/2022/04/Butterfly.png",
    visits: 26609,
    disallowComment: false,
    password: "",
    template: "theme",
    topPriority: 0,
    likes: 0,
    wordCount: 773,
    inProgress: false,
    commentCount: 33,
    tags: [
      {
        id: 1,
        name: "主题",
        slug: "themes",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1580914893201,
        fullPath: "https://halo.run/tags/themes.html",
      },
      {
        id: 3,
        name: "模板",
        slug: "templates",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502785043,
        fullPath: "https://halo.run/tags/templates.html",
      },
      {
        id: 4,
        name: "Halo 主题",
        slug: "halo-themes",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502798309,
        fullPath: "https://halo.run/tags/halo-themes.html",
      },
      {
        id: 5,
        name: "Halo 模板",
        slug: "halo-templates",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502800759,
        fullPath: "https://halo.run/tags/halo-templates.html",
      },
    ],
    categories: [
      {
        id: 2,
        name: "主题仓库",
        slug: "themes",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1580904752816,
        fullPath: "https://halo.run/categories/themes.html",
        priority: 1,
      },
    ],
    metas: {
      theme_repo: "https://github.com/dhjddcn/halo-theme-butterfly",
      theme_require: "1.4.11",
      theme_id: "butterfly",
      theme_author: "dhjddcn",
      theme_description: "Butterfly 主题 Halo 移植版",
      theme_version: "1.0.0",
    },
    topped: false,
  },
  {
    id: 383,
    title: "Joe 2.0",
    status: "PUBLISHED",
    slug: "joe20",
    editorType: "MARKDOWN",
    updateTime: 1649678688968,
    createTime: 1636638704064,
    editTime: 1649678688959,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/joe20.html",
    summary:
      "        Joe 主题 Halo 移植版                                Joe2.0 为 Typecho Themes Joe 主题的 Halo 版，由于 社区 之前有兄弟移植过，这次就叫 Joe2.0 吧，此次在原版主题上做了不少修改和适配，由原版的 php ",
    thumbnail: "https://halo.run/upload/2022/04/joe2.0.png",
    visits: 26444,
    disallowComment: false,
    password: "",
    template: "theme",
    topPriority: 0,
    likes: 0,
    wordCount: 8819,
    inProgress: false,
    commentCount: 59,
    tags: [
      {
        id: 1,
        name: "主题",
        slug: "themes",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1580914893201,
        fullPath: "https://halo.run/tags/themes.html",
      },
      {
        id: 3,
        name: "模板",
        slug: "templates",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502785043,
        fullPath: "https://halo.run/tags/templates.html",
      },
      {
        id: 4,
        name: "Halo 主题",
        slug: "halo-themes",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502798309,
        fullPath: "https://halo.run/tags/halo-themes.html",
      },
      {
        id: 5,
        name: "Halo 模板",
        slug: "halo-templates",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502800759,
        fullPath: "https://halo.run/tags/halo-templates.html",
      },
    ],
    categories: [
      {
        id: 2,
        name: "主题仓库",
        slug: "themes",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1580904752816,
        fullPath: "https://halo.run/categories/themes.html",
        priority: 1,
      },
    ],
    metas: {
      theme_repo: "https://github.com/qinhua/halo-theme-joe2.0",
      theme_require: "1.4.11",
      theme_id: "joe2.0",
      theme_author: "qinhua",
      theme_description: "Joe 主题 Halo 移植版",
      theme_version: "1.0.8",
    },
    topped: false,
  },
  {
    id: 351,
    title: "Halo 1.4.12 发布",
    status: "PUBLISHED",
    slug: "halo-1412-released",
    editorType: "MARKDOWN",
    updateTime: 1631798064866,
    createTime: 1631798054886,
    editTime: 1631798064862,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-1412-released.html",
    summary:
      "FeaturesMinio 存储提供 Region 设置项。#1440 halo-dev/halo-admin#346Improvements后台菜单列表提供拖动按钮，优化拖动排序的体验。halo-dev/halo-admin#350后台升级 CodeMirror 的版本，降低最终构建体积。halo",
    thumbnail:
      "https://halo.run/upload/2021/09/1.4.12-9ed1f548565f482f8ae0d1db89c07087.png",
    visits: 9306,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 467,
    inProgress: false,
    commentCount: 11,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 320,
    title: "Halo 1.4.10 发布",
    status: "PUBLISHED",
    slug: "halo-1410-released",
    editorType: "MARKDOWN",
    updateTime: 1626780018282,
    createTime: 1626625488791,
    editTime: 1626780018280,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-1410-released.html",
    summary:
      "Features编辑器支持脚注语法。halo-dev/halo#1406 halo-dev/halo-admin#341Improvements优化文章字数计算。halo-dev/halo#1354Content Api 中的获取文章列表支持传入关键字和分类 id 筛选项。halo-dev/halo",
    thumbnail:
      "https://halo.run/upload/2021/07/1.4.10-d530fa68c73048a4926da0e98ddb5f21.png",
    visits: 4804,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 1737,
    inProgress: false,
    commentCount: 7,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 319,
    title: "Reflect Halo 小程序",
    status: "PUBLISHED",
    slug: "mp-reflect",
    editorType: "MARKDOWN",
    updateTime: 1649679428953,
    createTime: 1623470692679,
    editTime: 1649679428942,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/mp-reflect.html",
    summary:
      "介绍Reflect Halo 是一个基于 Halo 后端的小程序项目，使用它可以非常便捷的搭建一个属于自己的博客小程序。主要特性符合大众审美的 UI 设计，我们拒绝使用一些花哨的界面或者动效，博客最重要的是阅读，我们力求打造更佳的阅读访问体验。同时我们执着于对细节的把控，力求不让强迫症患者感到不适。",
    thumbnail: "https://halo.run/upload/2022/04/reflect-mp-halo.jpeg",
    visits: 26117,
    disallowComment: false,
    password: "",
    template: "theme",
    topPriority: 0,
    likes: 0,
    wordCount: 1531,
    inProgress: false,
    commentCount: 10,
    tags: [],
    categories: [
      {
        id: 2,
        name: "主题仓库",
        slug: "themes",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1580904752816,
        fullPath: "https://halo.run/categories/themes.html",
        priority: 1,
      },
    ],
    metas: {
      theme_repo: "https://mianbaoduo.com/o/bread/mbd-YZqVl5pv",
      theme_require: "1.4.8",
      theme_id: "reflect.mp.halo",
      theme_author: "Reflect Team",
      theme_description: "Reflect Team 开发的 Halo 小程序",
      theme_version: "1.0.0",
    },
    topped: false,
  },
  {
    id: 289,
    title: "Iwtwin",
    status: "PUBLISHED",
    slug: "theme-iwtwin",
    editorType: "MARKDOWN",
    updateTime: 1649679443407,
    createTime: 1622203962900,
    editTime: 1649679443403,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/theme-iwtwin.html",
    summary:
      "IwtwinA Simple Halo Themes 预览在线预览https://www.kuya123.com图片预览安装压缩包上传方式（推荐）下载最新发行版zip压缩包到本地进入博客后台-外观-主题-安装选择本地上传，将压缩包上传上去等待提示安装完成在线拉取方式进入博客后台-外观-主题-安装选择",
    thumbnail: "https://halo.run/upload/2022/04/Iwtwin.png",
    visits: 22856,
    disallowComment: false,
    password: "",
    template: "theme",
    topPriority: 0,
    likes: 0,
    wordCount: 275,
    inProgress: false,
    commentCount: 17,
    tags: [
      {
        id: 1,
        name: "主题",
        slug: "themes",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1580914893201,
        fullPath: "https://halo.run/tags/themes.html",
      },
      {
        id: 3,
        name: "模板",
        slug: "templates",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502785043,
        fullPath: "https://halo.run/tags/templates.html",
      },
      {
        id: 4,
        name: "Halo 主题",
        slug: "halo-themes",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502798309,
        fullPath: "https://halo.run/tags/halo-themes.html",
      },
      {
        id: 5,
        name: "Halo 模板",
        slug: "halo-templates",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502800759,
        fullPath: "https://halo.run/tags/halo-templates.html",
      },
    ],
    categories: [
      {
        id: 2,
        name: "主题仓库",
        slug: "themes",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1580904752816,
        fullPath: "https://halo.run/categories/themes.html",
        priority: 1,
      },
    ],
    metas: {
      theme_repo: "https://github.com/cross266/halo-theme-iwtwin",
      theme_require: "1.4.8",
      theme_id: "iwtwin",
      theme_author: "CROSS",
      theme_description: "A Simple Halo Theme",
      theme_version: "1.0",
    },
    topped: false,
  },
  {
    id: 287,
    title: "使用腾讯云·云托管一键搭建 Halo",
    status: "PUBLISHED",
    slug: "tencent-cloudbase-halo",
    editorType: "MARKDOWN",
    updateTime: 1649580513991,
    createTime: 1620562541772,
    editTime: 1649580513973,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/tencent-cloudbase-halo.html",
    summary:
      "腾讯云·云开发简介云开发（Tencent CloudBase，TCB）是腾讯云提供的云原生一体化开发环境和工具平台，为开发者提供高可用、自动弹性扩缩的后端云服务，包含计算、存储、托管等 Serverless 化能力，可用于云端一体化开发多种端应用（小程序、公众号、Web 应用、Flutter 客户端",
    thumbnail:
      "https://halo.run/upload/2021/05/tencent-cloudbase-halo-61d41c4c35784df293f6b7dc675254a4.png",
    visits: 8992,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 951,
    inProgress: false,
    commentCount: 8,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 255,
    title: "Halo 1.4.8 发布",
    status: "PUBLISHED",
    slug: "halo-148-released",
    editorType: "MARKDOWN",
    updateTime: 1617953751589,
    createTime: 1617952738451,
    editTime: 1617953751588,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-148-released.html",
    summary:
      "Features系统设置中支持设置 Gravatar 源地址。#1331 halo-dev/halo-admin#314Improvements优化 RSS 订阅最后更新时间字段。#1342Bug Fixes修复在 1.4.7 中，导入 Markdown 提示格式不正确的问题。halo-dev/ha",
    thumbnail:
      "https://halo.run/upload/2021/04/1.4.8-186dddabdfd24be68fbd43c24dc91c22.png",
    visits: 7031,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 810,
    inProgress: false,
    commentCount: 20,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 223,
    title: "Halo 1.4.7 发布",
    status: "PUBLISHED",
    slug: "halo-147-released",
    editorType: "MARKDOWN",
    updateTime: 1615698491995,
    createTime: 1615698392006,
    editTime: 1615698491993,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-147-released.html",
    summary:
      "Bug Fixes修复在 Windows 平台下，上传主题压缩包提示不支持当前文件格式的问题。halo-dev/halo-admin#309Upgrade guidehttps://docs.halo.run/install/upgrade",
    thumbnail:
      "https://halo.run/upload/2021/03/1.4.7-b0e7be88d7ae4a7888f3750e92a105e9.png",
    visits: 4269,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 228,
    inProgress: false,
    commentCount: 5,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 191,
    title: "Halo 1.4.6 发布",
    status: "PUBLISHED",
    slug: "halo-146-released",
    editorType: "MARKDOWN",
    updateTime: 1615128686265,
    createTime: 1615121994495,
    editTime: 1615128686264,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-146-released.html",
    summary:
      "Features主题编写支持继承以及 block 特性。halo-dev/halo#1295Improvements重构初始化页面，目前分为全新安装和数据导入。从这个版本开始，数据导入将导入所有数据。halo-dev/halo-admin#296优化后台菜单管理的排序拖动体验。halo-dev/ha",
    thumbnail:
      "https://halo.run/upload/2021/03/1.4.6-df507013b5c74201b85ff19d99b6be27.png",
    visits: 2620,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 1208,
    inProgress: false,
    commentCount: 1,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 160,
    title: "Halo 1.4.5 发布",
    status: "PUBLISHED",
    slug: "halo-145-released",
    editorType: "MARKDOWN",
    updateTime: 1612787764475,
    createTime: 1612787374387,
    editTime: 1612787764473,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-145-released.html",
    summary:
      "Improvementssitemap.xml 新增所有分类和标签的链接。#1267Bug Fixes修复后台因为垂直滚动条导致界面抖动的问题。halo-dev/halo-admin#293修复加密分类页面输入密码后重定向的页面链接不正确的问题。#1264Upgrade guidehttps://d",
    thumbnail:
      "https://halo.run/upload/2021/02/1.4.5-543af0f9550e4d88ac94264aff4785a9.png",
    visits: 3480,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 205,
    inProgress: false,
    commentCount: 10,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 159,
    title: "Halo 1.4.4 发布",
    status: "PUBLISHED",
    slug: "halo-144-released",
    editorType: "MARKDOWN",
    updateTime: 1612710237186,
    createTime: 1612706024825,
    editTime: 1612710237183,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-144-released.html",
    summary:
      "Features支持对分类目录进行加密。#1235Bug Fixes修复在保存博客设置的时候，主题被恢复为上一个激活主题的问题。#1256修复后台在某些场景下，顶部加载条无法关闭的问题。",
    thumbnail:
      "https://halo.run/upload/2021/02/1.4.4-1a9b3c29f37045b19764fcccc732f7be.png",
    visits: 1626,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 170,
    inProgress: false,
    commentCount: 0,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 127,
    title: "Halo 1.4.3 发布",
    status: "PUBLISHED",
    slug: "halo-143-released",
    editorType: "MARKDOWN",
    updateTime: 1611768562878,
    createTime: 1611768239977,
    editTime: 1611768562872,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-143-released.html",
    summary:
      "随着这个版本的发布，我们的官网和文档也发生了一些变更。变更之后和 Halo 相关的站点：官网：https://halo.run文档：https://docs.halo.run论坛：https://bbs.halo.run主题仓库：https://halo.run/themes.htmlBreakin",
    thumbnail:
      "https://halo.run/upload/2021/01/1.4.3-b5fc5c3adfe543e5a2f01b53be241c5d.png",
    visits: 2438,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 793,
    inProgress: false,
    commentCount: 2,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 95,
    title: "Xue",
    status: "PUBLISHED",
    slug: "theme-xue",
    editorType: "MARKDOWN",
    updateTime: 1649679459916,
    createTime: 1609208959025,
    editTime: 1649679459907,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/theme-xue.html",
    summary:
      "Halo Theme Xue追求个性与至简说明开始预览示例站点文档主题特性更新日志预览Preview | 个人网站我的个人网站由于存在自定义，会和当前主题会有不同示例站点微服务驿站南国薏米通往体面生活的路上pengzhenjin's blognEo.一只从代码中寻找乐趣的猿千与千寻Symon's B",
    thumbnail: "https://halo.run/upload/2022/04/xue.png",
    visits: 48675,
    disallowComment: false,
    password: "",
    template: "theme",
    topPriority: 0,
    likes: 0,
    wordCount: 546,
    inProgress: false,
    commentCount: 40,
    tags: [
      {
        id: 1,
        name: "主题",
        slug: "themes",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1580914893201,
        fullPath: "https://halo.run/tags/themes.html",
      },
      {
        id: 3,
        name: "模板",
        slug: "templates",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502785043,
        fullPath: "https://halo.run/tags/templates.html",
      },
      {
        id: 4,
        name: "Halo 主题",
        slug: "halo-themes",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502798309,
        fullPath: "https://halo.run/tags/halo-themes.html",
      },
      {
        id: 5,
        name: "Halo 模板",
        slug: "halo-templates",
        color: "#cfd3d7",
        thumbnail: "",
        createTime: 1584502800759,
        fullPath: "https://halo.run/tags/halo-templates.html",
      },
    ],
    categories: [
      {
        id: 2,
        name: "主题仓库",
        slug: "themes",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1580904752816,
        fullPath: "https://halo.run/categories/themes.html",
        priority: 1,
      },
    ],
    metas: {
      theme_repo: "https://github.com/xzhuz/halo-theme-xue",
      theme_id: "bao",
      theme_author: "xzhuz",
      theme_description: "追求个性与至简",
      theme_version: "1.4.0",
    },
    topped: false,
  },
  {
    id: 94,
    title: "Halo 1.4.2 发布",
    status: "PUBLISHED",
    slug: "halo-142-released",
    editorType: "MARKDOWN",
    updateTime: 1611477431760,
    createTime: 1604368978521,
    editTime: 1611477431757,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-142-released.html",
    summary:
      "Feature文章固定链接支持年份型。#1095支持添加或修改友链时校验 name 和 url 是否重复。#1079支持 MinIO 云存储。#1097支持删除主题时，可选是否删除相关配置。#1105支持设置定时清理回收站的文章。#1114重构后台菜单管理，更方便的管理菜单分组以及排序。#1120F",
    thumbnail:
      "https://halo.run/upload/2021/01/1.4.2-54891c9f84f34ff98897b8320b666d8e.png",
    visits: 6432,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 792,
    inProgress: false,
    commentCount: 0,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
  {
    id: 93,
    title: "Halo 1.4.0 发布",
    status: "PUBLISHED",
    slug: "halo-140-released",
    editorType: "MARKDOWN",
    updateTime: 1611477443335,
    createTime: 1600878496716,
    editTime: 1611477443334,
    metaKeywords: null,
    metaDescription: null,
    fullPath: "https://halo.run/archives/halo-140-released.html",
    summary:
      "Feature支持静态存储重命名和修改文件内容。#819所有附件列表均支持右键复制图片链接。halo-dev/halo-admin#180开发者选项中的实时日志支持自动滚动到最新的日志。在线下载主题支持选择分支和 release。#515 #592 #835评论内容支持显示 html 文本。halo",
    thumbnail:
      "https://halo.run/upload/2021/01/1.4.0-e31ee60919d4441eb5a0c2c306fdfe48.png",
    visits: 3660,
    disallowComment: false,
    password: "",
    template: "",
    topPriority: 0,
    likes: 0,
    wordCount: 2270,
    inProgress: false,
    commentCount: 0,
    tags: [],
    categories: [
      {
        id: 9,
        name: "博客",
        slug: "blog",
        description: "",
        thumbnail: "",
        parentId: 0,
        password: null,
        createTime: 1581682496632,
        fullPath: "https://halo.run/categories/blog.html",
        priority: 8,
      },
    ],
    metas: {},
    topped: false,
  },
];
