name: Needs More Info Closer
on:
  schedule:
    - cron: 20 11 * * * # 4:20am Redmond
  repository_dispatch:
    types: [trigger-needs-more-info]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "microsoft/vscode-github-triage-actions"
          path: ./actions
          ref: stable
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Needs More Info Closer
        uses: ./actions/needs-more-info-closer
        with:
          token: ${{secrets.ISSUE_TRIAGE_BOT_PAT}}
          label: needs more info
          closeDays: 7
          additionalTeam: "ruibaby|JohnNiang|guqing|LIlGG|halo-dev-bot"
          closeComment: "此问题已自动关闭，因为它需要更多信息且最近没有活跃。"
          pingDays: 80
          pingComment: "Hey @${assignee}， 这个问题可能需要进一步关注。\n\n@${author}， 如果问题不再存在，您可以帮助我们关闭此问题，或者添加更多信息。"