name: On Label
on:
  issues:
    types: [labeled]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "microsoft/vscode-github-triage-actions"
          ref: stable
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions

      # source of truth in ./author-verified.yml
      - name: Run Author Verified
        if: contains(github.event.issue.labels.*.name, 'author-verification-requested')
        uses: ./actions/author-verified
        with:
          token: ${{secrets.ISSUE_TRIAGE_BOT_PAT}}
          requestVerificationComment: "该问题已在最新版本中修复!\n\n@${author}，请在今天或者稍晚确认你的使用的版本是否包含该提交： ${commit}，如果这件事已按预期得到解决，您可以通过评论 `/verified` 来帮助我们标记此问题。\n\n如果该问题仍然没有得到解决， 可以在评论中留下你希望得到的预期结果。"
          verifiedLabel: verified
          authorVerificationRequestedLabel: author-verification-requested


      # also make changes in ./on-comment.yml
      - name: Run Commands
        uses: ./actions/commands
        with:
          token: ${{secrets.ISSUE_TRIAGE_BOT_PAT}}
          config-path: commands

      # only here.
      - name: Run Subscribers
        uses: ./actions/topic-subscribe
        with:
          token: ${{secrets.ISSUE_TRIAGE_BOT_PAT}}
          config-path: subscribers